id: introduce_migration
learningObjectives:
  - Understand the concept of data migration in TypeORM
hints:
  - Data migration involves updating the database schema and data.
  - TypeORM provides tools to manage migrations efficiently.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Alright, let's talk about data migration. In this quest, we'll add a new
              `birthday` field to the User entity. This involves updating the
              database schema and ensuring our application code reflects these
              changes. Check out [TypeORM Migrations](https://typeorm.io/#/migrations) for more details.
          - text: Once you're ready, click the button below to proceed.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: Awesome! Let's get started with the migration process.
      - actionId: finish_step
