id: update_user_entity
learningObjectives:
  - Add a new field to the User entity
hints:
  - Look for the User entity in the codebase.
  - Add a new column for the birthday field.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Let's start by updating the User entity to include a new `birthday` field.
              This will involve adding a new column to the User entity class.
              Once you've made the changes, :instruction[open a pull request] so I can take a
              look.

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    do:
      - actionId: github_pr_review
        params:
          messages:
            person: lucca
            approved: "Great job! The User entity has been updated successfully."