id: create_migration_file
learningObjectives:
  - Generate and apply a migration file
hints:
  - Use TypeORM CLI to generate a migration file.
  - Ensure the migration file reflects the new 'birthday' column.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Now, let's create a migration file to update the database schema. Use the
              TypeORM CLI to generate a migration file that adds the 'birthday'
              column to the users table. Once done, open a pull request with
              your changes.
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Reviewing your migration file now.
            - actionId: github_pr_comment
              params:
                person: lucca
                message: Reviewing your migration file now.
        github_pr_workflow_complete_success:
          do:
            - actionId: github_pr_review
              params:
                solution: The migration file should add a 'birthday' column to the users table.
                messages:
                  person: lucca
                  approved: Great job! Let's merge it.
        github_pr_merged:
          do:
            - actionId: finish_step
