id: migration_quiz
learningObjectives:
  - Verify understanding of data migration concepts
hints:
  - Think about the steps involved in a typical migration.
  - Consider both schema and data changes.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Before we proceed, let's test your understanding of data migration. What
              are the key steps involved in a data migration process?
          - components:
              - type: form
                form:
                  id: migration_quiz
                  type: single_select_form
                  display:
                    type: tiles
                    properties:
                      columns: 3
                  options:
                    - label: Update schema, modify code, migrate data
                      value: correct
                      variant: secondary
                    - label: Only update schema
                      value: incorrect
                      variant: secondary
                    - label: Only modify code
                      value: incorrect
                      variant: secondary
trigger:
  type: chat_form_submitted
  flowNode:
    if:
      conditions:
        - conditionId: text_contains_strings
          params:
            text: ${formSubmission}
            strings:
              - correct
      then:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: You got it! Let's move on to the actual migration.
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: Not quite. Remember, a full migration involves updating the schema,
                    modifying the code, and migrating the data. Try again!
                - components:
                    - type: form
                      form:
                        id: migration_quiz
                        type: single_select_form
                        display:
                          type: tiles
                          properties:
                            columns: 3
                        options:
                          - label: Update schema, modify code, migrate data
                            value: correct
                            variant: secondary
                          - label: Only update schema
                            value: incorrect
                            variant: secondary
                          - label: Only modify code
                            value: incorrect
                            variant: secondary
