id: update_frontend
learningObjectives:
  - Reflect the new field in the frontend
hints:
  - Ensure the frontend form includes a field for the birthday.
  - Update any relevant components to handle the new data.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Finally, let's update the frontend to include the new 'birthday' field.
              Make sure the user interface reflects this change, and open a pull
              request with your updates.
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Let's see how the frontend looks with the new changes.
            - actionId: github_pr_comment
              params:
                person: lucca
                message: Let's see how the frontend looks with the new changes.
        github_pr_workflow_complete_success:
          do:
            - actionId: github_pr_review
              params:
                solution: Ensure the frontend includes a field for 'birthday'.
                messages:
                  person: lucca
                  approved: Nice work! Everything is in place.
        github_pr_merged:
          do:
            - actionId: finish_step
